
PREFIX dhs:    <https://civic-data.de/dhs#>
PREFIX schema: <http://schema.org/>
PREFIX locn:   <http://www.w3.org/ns/locn#>
PREFIX cdf:    <https://civic-data.de/federated-directory#>

INSERT {
    GRAPH <urn:federated> {
        ?fedIri
            schema:address    ?fullAddress ;
            locn:thoroughfare ?street      ;
            locn:postCode     ?postalCode  ;
            locn:postName     ?locality    .
    }
} WHERE {
    GRAPH <urn:source:dhs> {
        ?entry
            dhs:detailLink ?detailLink ;
            dhs:strasse    ?street     ;
            dhs:plzort     ?plzort     .
    }
    BIND(STRBEFORE(STRAFTER(?detailLink, "%5Bentry%5D="), "&") AS ?entryId)
    BIND(IRI(CONCAT(STR(cdf:), "dhs-", ?entryId))              AS ?fedIri)

    BIND(STRBEFORE(?plzort, " ")         AS ?postalCode)
    BIND(STRAFTER(?plzort, " ")          AS ?locality)
    BIND(CONCAT(?street, " - ", ?plzort) AS ?fullAddress)
}
