# Teaser format: "<Street> - <PLZ> <City>". Street may itself contain " - "
# (e.g. "Str. 5 - 11"), so anchor the split on the 5-digit postal code.

PREFIX xyz:    <http://sparql.xyz/facade-x/data/>
PREFIX schema: <http://schema.org/>
PREFIX locn:   <http://www.w3.org/ns/locn#>
PREFIX cdp:    <https://civic-data.de/pipeline#>

INSERT {
    GRAPH <urn:federated> {
        ?fedIri
            schema:address    ?teaser     ;
            locn:thoroughfare ?street     ;
            locn:postCode     ?postalCode ;
            locn:postName     ?locality   .
    }
} WHERE {
    GRAPH <urn:source:caritas> {
        ?entry
            xyz:Guid   ?guid   ;
            xyz:Teaser ?teaser .
        FILTER(isLiteral(?teaser) && ?teaser != "")
        FILTER(REGEX(?teaser, "^.+ - \\d{5} .+$"))
    }
    BIND(IRI(CONCAT(STR(cdp:), "caritas-", ?guid))        AS ?fedIri)

    BIND(REPLACE(?teaser, "^(.*) - (\\d{5}) (.*)$", "$1") AS ?street)
    BIND(REPLACE(?teaser, "^(.*) - (\\d{5}) (.*)$", "$2") AS ?postalCode)
    BIND(REPLACE(?teaser, "^(.*) - (\\d{5}) (.*)$", "$3") AS ?locality)
}
