PREFIX xyz:    <http://sparql.xyz/facade-x/data/>
PREFIX schema: <http://schema.org/>
PREFIX cdp:    <https://civic-data.de/pipeline#>

INSERT {
    GRAPH <urn:mapped> {
        ?org
            cdp:fromSource         cdp:dhsSource ;
            schema:streetAddress   ?street       ;
            schema:postalCode      ?postalCode   ;
            schema:addressLocality ?locality     .
    }
} WHERE {
    GRAPH <urn:source:dhs> {
        ?org
            cdp:fromSource cdp:dhsSource ;
            xyz:strasse    ?streetRaw    ;
            xyz:plzort     ?plzort       .
    }
    BIND(REPLACE(?streetRaw, "([Ss])tr\\.\\s*", "$1traße ") AS ?street)
    BIND(STRBEFORE(?plzort, " ") AS ?postalCode)
    BIND(STRAFTER(?plzort, " ")  AS ?locality)
}
