# entryId is extracted from the detailLink URL parameter %5Bentry%5D= (%5B=[, %5D=]).

PREFIX dhs:    <https://civic-data.de/dhs#>
PREFIX schema: <http://schema.org/>
PREFIX cdp:    <https://civic-data.de/pipeline#>

INSERT {
    GRAPH <urn:mapped> {
        ?fedIri
            schema:identifier ?entryId    ;
            schema:name       ?name       ;
            schema:url        ?detailLink .
    }
} WHERE {
    GRAPH <urn:source:dhs> {
        ?entry
            dhs:name       ?name       ;
            dhs:detailLink ?detailLink .
    }
    BIND(STRBEFORE(STRAFTER(?detailLink, "%5Bentry%5D="), "&") AS ?entryId)
    BIND(IRI(CONCAT(STR(cdp:), "dhs-", ?entryId))              AS ?fedIri)
}
